//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemonito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeByHeadquarter
    {
        public long IdEmployee { get; set; }
        public long IdHeadquarter { get; set; }
        public System.DateTime DateUbication { get; set; }
        public bool IsActualUbication { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Headquarters Headquarters { get; set; }
    }
}
