//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemonito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrizeTicket
    {
        public long IdClient { get; set; }
        public int Points { get; set; }
        public System.DateTime DatePrize { get; set; }
        public bool IsAvailable { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
