//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinemonito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.MoviesByRoom = new HashSet<MoviesByRoom>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int GeneralChairAmount { get; set; }
        public int PreferentialChairAmount { get; set; }
        public long IdHeadquarter { get; set; }
    
        public virtual Headquarters Headquarters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoviesByRoom> MoviesByRoom { get; set; }
    }
}
